# Generated by Django 3.0.8 on 2020-07-03 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branches',
            name='id',
        ),
        migrations.AlterField(
            model_name='branches',
            name='ifsc',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
        ),
    ]
