# Generated by Django 3.0.8 on 2020-07-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0002_auto_20200703_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='bank_id',
            new_name='bank',
        ),
    ]
